#!/bin/bash

function generatekeys {
  for host in $hosts; do
    echo $host
    shost=`echo $host | cut -d . -f 1`
    keytool -genkey -noprompt -alias gateway-identity -keyalg RSA -dname "CN=$host, OU=$OU, O=$O, L=$L, S=$S, C=$C" -keystore $shost.jks -storepass "$KEYPASS"  -keypass "$KEYPASS"
  done
}

function generatecsr {
  for host in $hosts; do
    echo $host
    shost=`echo $host | cut -d . -f 1`
    keytool -certreq -noprompt -alias gateway-identity -keyalg RSA -keystore $shost.jks -storepass "$KEYPASS"  -keypass "$KEYPASS" > $shost.csr
  done
}

function importcert {
  for host in $hosts; do
    shost=`echo $host |cut -d . -f 1`
    for cert in `ls ca/`; do
      keytool -importcert -noprompt -file ca/$cert -alias $cert  -keystore $shost.jks -storepass "$KEYPASS"
    done
    keytool -importcert -noprompt -alias gateway-identity -file $shost.cer -keystore $shost.jks -storepass "$KEYPASS"
  done

}

function signcsrs {
  for host in $hosts; do
    echo $host
    shost=`echo $host |cut -d . -f 1`
    openssl x509 -req -in $shost.csr -CA $domain.cer -CAkey $domain.key -CAcreateserial -out $shost.cer -days 1024 -sha256
  done
}

function generateca {
  openssl req -new -newkey rsa:2048 -days 365 -nodes -x509 \
      -subj "/C=$C/ST=$S/L=$L/O=$O/CN=$domain" \
      -keyout $domain.key  -out $domain.cer
  mkdir -p ca/
  cp $domain.cer ca/
}

function generatetruststore {
  for cert in `ls ca/`; do
    keytool -importcert -noprompt -file ca/$cert -alias $cert -keystore truststore.jks -storepass "$TRUSTPASS"
  done
}

function generatepems {
  for host in $hosts; do
    echo $host
    shost=`echo $host | cut -d . -f 1`
    keytool -importkeystore -srckeystore $shost.jks \
      -srcstorepass "$KEYPASS" -srckeypass "$KEYPASS" -destkeystore $shost.p12 \
      -deststoretype PKCS12 -srcalias gateway-identity -deststorepass "$KEYPASS" -destkeypass "$KEYPASS"
    openssl pkcs12 -in $shost.p12 -passin pass:$KEYPASS  -nokeys -out $shost.pem
    openssl pkcs12 -in $shost.p12 -passin pass:$KEYPASS -nocerts -out $shost.key
    #rm -f $shost.p12
  done
}

function pushkeys {
  for host in $hosts; do
    if [ $host != "ranger.$domain" ]; then
      ssh $host mkdir -p $KEYLOC\; chmod ugo+rx $KEYLOC
      ssh $host mkdir -p $TRUSTLOC\; chmod ugo+rx $TRUSTLOC
      rsync -arP $shost.jks $host:${KEYLOC}/server.jks
      rsync -arP truststore.jks $host:${TRUSTLOC}/truststore.jks
      rsync -arP $shost.cer $host:${KEYLOC}/server.pem
      rsync -arP $shost.key $host:${KEYLOC}/server.key
      rsync -arP ranger.jks $host:${KEYLOC}/ranger-plugin.jks
    fi
  done
}

if [ -z $1 ]; then
  echo -e "Usage: $0 [CHOICE] [CONFIGFile] {LocalAuthority|LocalAuthority|RemoteAuthorityImportCertsAndPush}\n LocalAuthority: Generate local CA, generate truststore and keystores, and push to servers.\n RemoteAuthorityGenerateCSR: Generate keystore and CSR's to be signed be a remote authority.\n RemoteAuthorityImportCertsAndPush: Import certs generated by remote authority. Naming should shorthostame.cer. RemoteAuthorityGenerateCSR must be run first and CSR's from that signed"
  exit 1
fi

config=$2

if [ -z $config ] && ! [ -s $config ]; then
  echo Configs file does not exist, specify as first argument
  exit 1
fi

hostsfile=`cat $config | grep HostFile | cut -d "=" -f 2`
if [ -z "$hostsfile" ] && ! [ -s "$hostsfile" ]; then
  echo Host file is not specified or empty
  exit 1
fi


OU=`cat $config | grep OrgUnit | cut -d "=" -f 2`
if [ -z $OU ]; then
  echo OrgUnit is not specified
  exit 1
fi

O=`cat $config | grep Organization | cut -d "=" -f 2`
if [ -z "$O" ]; then
  echo Organization is not specified
  exit 1
fi

L=`cat $config | grep City | cut -d "=" -f 2 `
if [ -z $L ]; then
  echo City is not specified
  exit 1
fi

S=`cat $config | grep State | cut -d "=" -f 2`
if [ -z $S ]; then
  echo State is not specified
  exit 1
fi

C=`cat $config | grep CountryCode | cut -d "=" -f 2`
if [ -z $C ]; then
  echo CountryCode is not specified
  exit 1
fi

KEYPASS=`cat $config | grep KeyStorePassword | cut -d "=" -f 2`
if [ -z $KEYPASS ]; then
  echo KeyStorePassword is not specified
  exit 1
fi

TRUSTPASS=`cat $config | grep TrustStorePassword | cut -d "=" -f 2`
if [ -z $TRUSTPASS ]; then
  echo TrustStorePassword is not specified
  exit 1
fi

KEYLOC=`cat $config | grep KeyStoreLocation | cut -d "=" -f 2`
if [ -z $KEYLOC ]; then
  echo KeyStoreLocation is not specified
  exit 1
fi

TRUSTLOC=`cat $config | grep TrustStoreLocation | cut -d "=" -f 2`
if [ -z $TRUSTLOC ]; then
  echo TrustStoreLocation is not specified
  exit 1
fi

domain=`cat $config | grep Domain | cut -d "=" -f 2`
if [ -z $domain ]; then
  echo Domain is not specified
  exit 1
fi

echo ranger.$domain >> $hostsfile
hosts=`cat $hostsfile`

mkdir -p ca

case $1 in
  LocalAuthority)
    generateca
    generatekeys
    generatecsr
    signcsrs
    generatetruststore
    importcert
    generatepems
    pushkeys
    ;;
  RemoteAuthorityGenerateCSR)
    generatekeys
    generatecsr
    ;;
  RemoteAuthorityImportCertsAndPush)
    importcert
    generatetruststore
    generatepems
    pushkeys
    ;;
  *)
    echo -e "Usage: $0 [CHOICE] [CONFIGFile] {LocalAuthority|LocalAuthority|RemoteAuthorityImportCertsAndPush}\n LocalAuthority: Generate local CA, generate truststore and keystores, and push to servers.\n RemoteAuthorityGenerateCSR: Generate keystore and CSR's to be signed be a remote authority.\n RemoteAuthorityImportCertsAndPush: Import certs generated by remote authority. Naming should shorthostame.cer. RemoteAuthorityGenerateCSR must be run first and CSR's from that signed"
    ;;
esac
